### ISSUE TITLE
Apply autosummary for module but not nested classes

### ISSUE THREAD

**Issue by piyushk** [Chilipp/autodocsumm#19]
I'm using autodocsumm along with sphinx-apidoc to generate documentation.

My current usage is as follows:
```
.. automodule:: {{ pkgname }}
   :members:
   :undoc-members:
   :inherited-members:
   :autosummary:
```

This creates the summary table as desired for the module, but also causes each class etc. in the package added by automodule to have a summary table, which is not desired. Is there an easy way I can get just the summary table for the module, and not for nested structures?

**Comment by Chilipp** [comment]
Hi piyushk! Unfortunately, no, not yet. I see that this feature can be useful and it would be good to implement it! It should not be too difficult.

Do you have any time that you can invest into this? I can work on it, but probably not much during the next four weeks since I am finishing my PhD. I am happy to discuss and review any new implementation.

**Comment by piyushk** [comment]
I'll take a look at it tomorrow. I haven't looked at the code in detail yet -- any quick pointers on how to implement the feature would be appreciated, but not necessary.

**Comment by piyushk** [comment]
I managed to find some time right now to look at this issue. I have opened a draft PR for this issue https://github.com/Chilipp/autodocsumm/pull/20 which attempts a fix. We can continue discussion there. I'm unsure if my solution is correct, as I do not have familiarity with sphinx or autodoc code.

We can also follow up at a later date when you're more available. I'm currently using my branch, so I'm not blocked.
